Repository sensu/sensu-puppet, pull requests merged in 2019-02, with the labels that each got.

#1060 Puppet v6 now uses Ruby v2.5.3
  .travis.yml
Labels: sensu v1

#1061 Puppet v6 now uses Ruby v2.5.3
  .travis.yml
Labels: sensu v2

#1063 Add Debian 8 and 9 support back
  .travis.yml
  README.md
  metadata.json
Labels: sensu v2

#1065 Support trusting CA cert with sensuctl
  .fixtures-latest.yml
  .fixtures.yml
  README.md
  lib/puppet/provider/sensu_configure/sensuctl.rb
  lib/puppet/type/sensu_configure.rb
  manifests/backend.pp
  metadata.json
  spec/classes/backend_spec.rb
  spec/unit/provider/sensu_configure/sensuctl_spec.rb
  spec/unit/sensu_configure_spec.rb
Labels: sensu v2

#1067 Add max_output_size and discard_output to sensu_check
  lib/puppet/type/sensu_check.rb
  spec/unit/sensu_check_spec.rb
Labels: sensu v2

#1062 Fix sensu facts to work with sensu-go 5.2.0 output
  lib/facter/sensu_facts.rb
  spec/unit/facter/sensu_facts_spec.rb
Labels: sensu v2

#1070 Fix package resources when manage_repo is false
  manifests/agent.pp
  manifests/backend.pp
  manifests/init.pp
  spec/classes/agent_spec.rb
  spec/classes/backend_spec.rb
Labels: sensu v2

#1071 Remove hardcoded /etc/sensu
  manifests/check.pp
  manifests/config.pp
  manifests/contact.pp
  manifests/extension.pp
  manifests/filter.pp
  manifests/mutator.pp
Labels: bug, sensu v1

#1073 (GH-893) Remove Vagrant box for windows with chocolatey provider
  Vagrantfile
  tests/sensu-client-windows-chocolatey.pp
Labels: sensu v1

#1079 Remove windows and mac vagrant and beaker setup, not supported
  Vagrantfile
  spec/acceptance/nodesets/windows-server-2012r2.yml
  tests/provision_basic_win.2.ps1
  tests/provision_basic_win.bat
  tests/provision_basic_win.ps1
  tests/provision_macos.sh
Labels: sensu v2

#1082 fixes: couldn't find login name expanding tilde (cont.)
  lib/puppet/provider/sensuctl.rb
  spec/unit/provider/sensu_configure/sensuctl_spec.rb
  spec/unit/provider/sensuctl_spec.rb
Labels: sensu v2

#1084 Remove dependency pinnings from Gemfile
  Gemfile
Labels: in progress, sensu v2

#1085 Remove unused dependencies from Gemfile
  Gemfile
Labels: in progress, sensu v2
