Repository sensu/sensu-puppet, pull requests merged in 2020-11, with the labels that each got.

#1285 [ci skip] Style updates to puppet code in README
  README.md
Labels: skip-changelog

#1286 Fix agent to use correct API URL for agent entity configs
  manifests/agent.pp
  spec/classes/backend_datastore_postgresql_spec.rb
Labels: bug

#1287 [ci skip] README updates for where to define resources
  README.md
Labels: enhancement
